/*
  ShinAI Website v2 — build.mjs（開発ツール。公開ディレクトリには含めない）
  partials と styles を読み、共有シェルへ結合して各ページの最終HTMLを生成する。
  - CSS は tokens→base→sections の順で styles/app.css に結合(リクエスト削減)。
  - partials/<page>.html(=main の中身) を <main id="main"> で正規化して挿入。
  - 共有 head/header/footer/chatbot を全ページへ。現在地ナビに aria-current を付与。
  実行: node _build/build.mjs
*/
import { readFileSync, writeFileSync, readdirSync, cpSync, mkdirSync, rmSync, copyFileSync, statSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { chunkPage, catalogChunk } from "./chunk.mjs";
import { encodeVector, normalizeVector } from "../api/lib/vector.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/* 鍵はマシンごとの .env.local から読む(.gitignore の .env.* に含まれる)。
   毎回入力させる方式は、マシンが増えるほど手順が人の記憶に依存する。
   忘れた回だけベクトルが付かない、という取りこぼしが起きる。
   既に環境変数があればそちらを優先する(CI・一時的な上書きを妨げない)。
   値は読むだけで、出力にもログにも出さない。 */
const loadLocalEnv = () => {
  const path = join(ROOT, ".env.local");
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!m) continue;
    const value = m[2].trim().replace(/^["']|["']$/g, "");
    if (value && !process.env[m[1]]) process.env[m[1]] = value;
  }
};
loadLocalEnv();

/* ビルドごとにGitハッシュをURLクエリに付加してブラウザキャッシュを無効化する。 */
const BUILD_HASH = (() => {
  try { return execSync("git rev-parse --short HEAD", { cwd: ROOT }).toString().trim(); }
  catch { return Date.now().toString(36); }
})();

/* ページの最終更新日。sitemap の lastmod と WebPage.dateModified の双方が
   これを使う(二か所に別々の日付が出ると、どちらが本当か判定できなくなる)。

   出所は「その本文ファイルを最後に変更したコミットの日付」。ビルド日時ではない。
   ビルドのたびに全ページが更新されたことになると、クローラは lastmod を信用しなくなる。
   git が無い環境(配布物からの再ビルド等)ではファイルの更新時刻へ退避する。 */
const lastModCache = new Map();
const lastModOf = (relPath) => {
  if (lastModCache.has(relPath)) return lastModCache.get(relPath);
  let date;
  try {
    const out = execSync(`git log -1 --format=%cs -- "${relPath}"`, { cwd: ROOT }).toString().trim();
    date = /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
  } catch { date = null; }
  if (!date) date = statSync(join(ROOT, relPath)).mtime.toISOString().slice(0, 10);
  lastModCache.set(relPath, date);
  return date;
};

/* 実ドメインを置く唯一の場所。OGP/canonical の絶対URLに使う。 */
const SITE_URL = "https://shinai-inc.jp";
/* OGPクローラ(LINE等)はURL単位でキャッシュするため、画像を変えるときはファイル名も変える */
const OG_IMAGE = SITE_URL + "/assets/images/ogp-card-logo.png";
/* 検索結果・ナレッジパネルで使われる企業ロゴ。共有カード(OG_IMAGE)とは用途が違う。
   OG_IMAGE は余白と文字を含む1200x630の絵で、ロゴとしては読み取れない。 */
const LOGO_IMAGE = SITE_URL + "/assets/images/logo.png";

/* 法人番号。国税庁が基本3情報(商号・所在地・法人番号)として公表しており、
   誰でも確認できる公開情報。文字列の一致ではなく公的登記との対応として
   自社を名乗れる、唯一の識別子である。同名他社(神奈川県のシンアイ株式会社)と
   取り違えられない根拠にもなる。 */
const CORPORATE_NUMBER = "9070001044403";
/* 公的データベース上の自社ページ。第三者が検証できる参照先を持たせる。 */
const OFFICIAL_REFERENCES = [
  `https://www.houjin-bangou.nta.go.jp/henkorireki-johoto.html?selHouzinNo=${CORPORATE_NUMBER}`,
  `https://info.gbiz.go.jp/hojin/ichiran?hojinBango=${CORPORATE_NUMBER}`
];
const CONTACT_EMAIL = "contact@shinai-inc.jp";
/* RFC 9116の脆弱性報告窓口。一般問い合わせ(CONTACT_EMAIL)とは意図的に分けている。 */
const SECURITY_CONTACT_EMAIL = "support@shinai-inc.jp";

/* チャットAPIのオリジン。connect-src の許可先であり、クライアントの接続先でもある。 */
const API_ORIGIN = "https://api.shinai-inc.jp";

/* ---- CSP は単一の定義から生成する ----
   以前は各HTMLの <meta> と deploy/_headers に同じ内容が独立して存在し、
   片方だけ直すと障害が潜伏する状態だった(metaだけ直すとホスティング移行時に
   無言で壊れ、_headersだけ直すと今すぐ壊れる)。ここを唯一の出所にする。
   meta形式は frame-ancestors と report-uri を解釈しないため、
   応答ヘッダ側にのみ足す(下の CSP_HEADER)。 */
/* Cloudflare Web Analytics のサイトトークン。
   HTMLに出る公開値であり秘密ではない（鍵と同じ扱いをしない）。
   本サイトは GitHub Pages 配信で Cloudflare はDNSのみのため、
   プロキシ経由の自動計測は使えず、ビーコンを手で埋め込む方式になる。
   空のあいだはビーコンもCSPの許可も出さない。計測しない構成のまま保つ。 */
const WEB_ANALYTICS_TOKEN = "";
const CF_BEACON_HOST = "https://static.cloudflareinsights.com";
const CF_BEACON_ENDPOINT = "https://cloudflareinsights.com";
const analyticsOn = WEB_ANALYTICS_TOKEN.length > 0;

const CSP_DIRECTIVES = [
  "default-src 'self'",
  `script-src 'self'${analyticsOn ? " " + CF_BEACON_HOST : ""}`,
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data:",
  `connect-src 'self' https://formspree.io ${API_ORIGIN}${analyticsOn ? " " + CF_BEACON_ENDPOINT : ""}`,
  "base-uri 'self'",
  "form-action 'self' https://formspree.io",
  "object-src 'none'"
];
const CSP_META = CSP_DIRECTIVES.join("; ");
const CSP_HEADER = CSP_DIRECTIVES
  .concat(["frame-ancestors 'none'", "upgrade-insecure-requests"])
  .join("; ");

const read = (p) => readFileSync(join(ROOT, p), "utf8");
const write = (p, c) => writeFileSync(join(ROOT, p), c, "utf8");

/* ---- 1. CSS 結合(tokens, base を先頭に) ---- */
const sectionsDir = join(ROOT, "styles", "sections");
const sectionFiles = readdirSync(sectionsDir).filter((f) => f.endsWith(".css")).sort();
let css = "/* Generated by _build/build.mjs — edit sources in styles/, not this file. */\n";
css += read("styles/tokens.css") + "\n";
css += read("styles/base.css") + "\n";
for (const f of sectionFiles) {
  css += "\n/* sections/" + f + " */\n" + read(join("styles", "sections", f)) + "\n";
}
write("styles/app.css", css);

/* ---- 2. ロケール定義 ----
   日本語はサイト直下、英語は /en/ 配下に出力する。既存の日本語URLを一切動かさずに
   英語版を増設でき、検索エンジンには言語ごとの独立URLとして正しくインデックスされる。
   dir     … SITE_URL からの出力先(末尾スラッシュ込み)
   prefix  … ページから見た共有アセット(styles/scripts/assets)への相対接頭辞
   src     … partial の読み込み元ディレクトリ */
const LOCALES = [
  { code: "ja", dir: "", prefix: "", src: "partials", htmlLang: "ja", ogLocale: "ja_JP",
    switchTo: "en", switchLabel: "English", switchAria: "Switch to English",
    manifestDesc: "企業の暗黙知を、使えるAI資産へ。" },
  { code: "en", dir: "en/", prefix: "../", src: "partials/en", htmlLang: "en", ogLocale: "en_US",
    switchTo: "ja", switchLabel: "日本語", switchAria: "日本語に切り替える",
    manifestDesc: "Turning your company's tacit knowledge into working AI assets." }
];

/* ページが公開される言語。page.locales 未指定なら全言語に出す。
   地域ページのように日本語でしか検索されないものは ["ja"] を指定し、
   英語版の生成・hreflang申告・sitemap収録・言語切替のすべてから外す。
   実体のない言語版を申告すると、申告そのものの信用が落ちる。 */
const localesFor = (page) =>
  LOCALES.filter((l) => !page.locales || page.locales.includes(l.code));

/* 言語切替UI。ヘッダーの {{LANG_SWITCH}} を置き換える。
   同一ページの他言語版へ1タップで移動する(トップへ飛ばさない)。
   他言語版を持たないページでは何も出さない(存在しないURLへは飛ばせない)。 */
const langSwitch = (loc, page) => {
  if (localesFor(page).length < 2) return "";
  const href = loc.code === "ja" ? "en/" + page.file : "../" + page.file;
  return `<a class="site-header__lang" href="${href}" hreflang="${loc.switchTo}" lang="${loc.switchTo}" aria-label="${loc.switchAria}">
        <svg class="site-header__lang-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.5"/>
          <path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18" stroke="currentColor" stroke-width="1.5"/>
        </svg>
        <span class="site-header__lang-label">${loc.switchLabel}</span>
      </a>`;
};

/* ロケールごとの共有 partial(ヘッダー/フッター/チャット)を読む。 */
const sharedFor = (loc) => ({
  header: read(loc.src + "/_header.html"),
  footer: read(loc.src + "/_footer.html").replace("{{YEAR}}", String(new Date().getFullYear())),
  chatbot: read(loc.src + "/_chatbot.html")
});
const shared = Object.fromEntries(LOCALES.map((l) => [l.code, sharedFor(l)]));

/* 現在地ナビに aria-current を付ける(最初の該当 href へ) */
const markCurrent = (html, nav) => {
  if (!nav) return html;
  const needle = `href="${nav}.html"`;
  const i = html.indexOf(needle);
  if (i === -1) return html;
  return html.slice(0, i + needle.length) + ' aria-current="page"' + html.slice(i + needle.length);
};

/* partials/<page> の <main> を正規化(既存の main タグを剥がして wrap し直す) */
const normalizeMain = (raw) =>
  raw.replace(/^\s*<main\b[^>]*>/i, "").replace(/<\/main>\s*$/i, "").trim();

/* ---- 3. ページ定義(sitemap の changefreq/priority もここで一元管理) ---- */
const pages = [
  { file: "index.html", part: "index.html", nav: null, hero: true,
    changefreq: "monthly", priority: "1.0",
    title: "ShinAI｜企業の暗黙知を、使えるAI資産へ",
    desc: "群馬県高崎市のAI開発会社。退職や属人化で失われる判断や知識を、現場で使える専用AIへ。文書に残らない現場の技を扱うフィジカルAIの研究開発（PoC）にも取り組んでいます。",
    /* SNS共有のプレビューは一瞬で読まれる。課題の描写から入らず
       「何をする会社か」を先頭で言い切る。検索結果用のdescとは役割が違う。 */
    ogDesc: "企業の構造変革を支援するAI企業｜シンアイ株式会社　企画設計・開発・運用まで一気通貫支援",
    en: { title: "ShinAI | Turn Your Company's Tacit Knowledge into Working AI",
          desc: "The judgment and know-how your company loses to retirement and key-person dependency, rebuilt as private AI that works on the floor. A Japan-based enterprise AI engineering partner, researching physical AI for the skill documents never captured.",
          ogDesc: "An AI company supporting structural change in business | ShinAI Inc. End-to-end support from service design through development to operations." } },
  { file: "services.html", part: "services.html", nav: "services", hero: false,
    crumb: "ソリューション",
    changefreq: "monthly", priority: "0.9",
    title: "ソリューション｜ShinAI",
    desc: "群馬県高崎市を拠点に、暗黙知のAI化、企業専用AIエージェント、AI化伴走支援、そしてフィジカルAIの研究開発（PoC）。集めて、つなぎ、現場で使えるところまで。ShinAIの提供領域と進め方。",
    en: {crumb: "Solutions",  title: "Solutions | ShinAI",
          desc: "Tacit knowledge structuring, private enterprise AI agents, hands-on support for AI-driven transformation, and physical AI research (PoC). Capture it, connect it, and make it usable where the work happens." } },
  { file: "industries.html", part: "industries.html", nav: "industries", hero: false,
    crumb: "業種別の活用",
    changefreq: "monthly", priority: "0.8",
    title: "業種別の活用｜ShinAI",
    desc: "製造、建設、介護や専門サービス、小売、医療福祉、教育、金融、不動産。業種ごとの困りごとと、暗黙知改善でどう変わるかの活用イメージ。群馬県高崎市のAI開発会社が、業種の文脈からAIの適用先を整理します。",
    en: {crumb: "Industries",  title: "Industries | ShinAI",
          desc: "Manufacturing, construction, care and professional services, retail, healthcare, education, finance, and real estate. What breaks in each, and how tacit-knowledge AI changes it." } },
  /* 地域ページ。トップの title はブランドの表現として据え置くと決めたため、
     地域クエリで戦える面はここにしかない。日本語のみで公開する。
     title には地域語を残しつつ、本文は「群馬発・全国へ」で書く。
     県内限定に読める書き方をすると、県外の読み手がそこで離れる。 */
  { file: "gunma-ai.html", part: "gunma-ai.html", nav: null, hero: false,
    locales: ["ja"],
    crumb: "群馬のAI導入支援",
    changefreq: "monthly", priority: "0.9",
    title: "群馬県のAI導入支援・AIシステム開発｜シンアイ株式会社（高崎市）",
    desc: "群馬県高崎市のAIシステム開発会社。生成AIの業務活用、RAG構築、企業専用AIエージェント開発、技能継承まで。研修や試験導入で終わらせず、企画から運用まで一気通貫してご支援します。群馬県を中心に全国対応・オンライン相談可。" },
  { file: "about.html", part: "about.html", nav: "about", hero: false,
    crumb: "会社情報",
    changefreq: "monthly", priority: "0.7",
    title: "会社情報｜ShinAI",
    desc: "技術より先に、人を見る。群馬県高崎市に本店を置くシンアイ株式会社の目的、代表メッセージ、七つのShin、体制と会社概要。",
    en: {crumb: "About",  title: "About | ShinAI",
          desc: "People before technology. Our purpose, a message from the founder, the Seven Shin principles, our team, and company facts." } },
  { file: "faq.html", part: "faq.html", nav: "faq", hero: false,
    crumb: "よくあるご質問",
    changefreq: "monthly", priority: "0.6",
    extraScripts: ['<script src="scripts/faq.js" defer></script>'],
    title: "よくあるご質問｜ShinAI",
    desc: "はじめての方へ、費用と導入、開発の進め方、業種別の活用、サービス、そのほか。群馬県高崎市のAI開発会社ShinAIへのよくある質問。",
    en: {crumb: "FAQ",  title: "FAQ | ShinAI",
          desc: "Getting started, cost and rollout, how we build, industry use, our services, and more. Common questions about working with ShinAI." } },
  { file: "contact.html", part: "contact.html", nav: "contact", hero: false,
    crumb: "お問い合わせ",
    changefreq: "monthly", priority: "0.8",
    extraScripts: ['<script src="scripts/contact-form.js" defer></script>'],
    title: "お問い合わせ・無料相談｜ShinAI",
    desc: "まだ要件が決まっていなくても構いません。現在の業務と知識資産から、AIの適用可能性を一緒に整理します。無料相談は30〜45分、事前準備は不要です。群馬県高崎市のAI開発会社が承ります。",
    en: {crumb: "Contact",  title: "Contact & Free Consultation | ShinAI",
          desc: "You do not need defined requirements to talk to us. We map where AI can apply from your current operations and knowledge assets. Free consultation, 30-45 minutes, no preparation needed." } },
  { file: "news.html", part: "news.html", nav: "news", hero: false,
    crumb: "お知らせ",
    changefreq: "monthly", priority: "0.6",
    title: "お知らせ｜ShinAI",
    desc: "シンアイ株式会社の登壇・発表・活動のお知らせ。群馬県高崎市を拠点に、暗黙知のAI化と企業専用AIエージェント開発に取り組んでいます。",
    en: {crumb: "News",  title: "News | ShinAI",
          desc: "Talks, announcements, and activities from ShinAI Inc. Based in Takasaki, Gunma, working on tacit-knowledge AI and private enterprise AI agents." } },
  { file: "news-20251205-takasaki-press.html", part: "news-20251205-takasaki-press.html",
    nav: "news", hero: false,
    crumb: "高崎商工会議所 第9回合同プレス発表会に登壇",
    crumbParent: { name: "お知らせ", file: "news.html" },
    article: { date: "2025-12-05", image: "assets/images/news-takasaki-press.jpg" },
    changefreq: "yearly", priority: "0.5",
    title: "高崎商工会議所 第9回合同プレス発表会に登壇しました｜ShinAI",
    desc: "2025年12月5日、高崎商工会議所の第9回合同プレス発表会にShinAI代表 柴田昌国が登壇し、「AIで人間らしい時間を取り戻す」という想いのもと、群馬県高崎市を拠点とする取り組みを発表しました。",
    en: {crumb: "Talk at the 9th Takasaki CCI joint press conference",
          crumbParent: { name: "News", file: "news.html" },
          title: "Talk at the 9th Takasaki CCI Joint Press Conference | ShinAI",
          desc: "On 5 December 2025, ShinAI founder Masakuni Shibata spoke at the 9th joint press conference of the Takasaki Chamber of Commerce and Industry, presenting the company's work under the idea of using AI to give people their human hours back." } },
  { file: "privacy.html", part: "privacy.html", nav: null, hero: false,
    crumb: "プライバシーポリシー",
    changefreq: "yearly", priority: "0.2",
    title: "プライバシーポリシー｜ShinAI",
    desc: "ShinAIの個人情報の取り扱いについて。",
    en: {crumb: "Privacy Policy",  title: "Privacy Policy | ShinAI",
          desc: "How ShinAI handles personal information." } },
  { file: "terms.html", part: "terms.html", nav: null, hero: false,
    crumb: "利用規約",
    changefreq: "yearly", priority: "0.2",
    title: "利用規約｜ShinAI",
    desc: "ShinAIウェブサイトの利用規約。",
    en: {crumb: "Terms of Use",  title: "Terms of Use | ShinAI",
          desc: "Terms of use for the ShinAI website." } }
];

const ldJson = {
  "@context": "https://schema.org",
  /* Organization だけでは「どこかにある会社」に留まる。ProfessionalService は
     LocalBusiness の下位型で、実在の所在地を持って役務を提供する主体であることを
     型そのもので示す。地域クエリで検索が探しているのはこの型の実体である。
     電話・営業時間は公開していないため申告しない(型のために無い値を埋めない)。 */
  "@type": ["Organization", "ProfessionalService"],
  "@id": SITE_URL + "/#organization",
  name: "シンアイ株式会社",
  legalName: "シンアイ株式会社",
  /* 指名検索の表記ゆれ(シンアイ/ShinAI/シンアイ株式会社)を同一主体として束ねる。 */
  alternateName: ["ShinAI", "シンアイ", "ShinAI Inc.", "シンアイ"],
  identifier: {
    "@type": "PropertyValue",
    propertyID: "法人番号",
    value: CORPORATE_NUMBER
  },
  sameAs: OFFICIAL_REFERENCES,
  url: SITE_URL + "/",
  email: CONTACT_EMAIL,
  logo: LOGO_IMAGE,
  image: LOGO_IMAGE,
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: CONTACT_EMAIL,
    availableLanguage: ["ja", "en"],
    areaServed: "JP"
  },
  slogan: "企業の暗黙知を、使えるAI資産へ。",
  description: "真の価値を信じ、次世代のために新たな未来を創る。ShinAIは、人の想いとAIをつなぎ、企業の「これまで」を大切に「これから」の変革に伴走する、企業AI開発特化のエンジニアチーム。強化学習・カスタムLLM最適化・RAG・オンプレミス対応により、暗黙知のAI化と企業専用AIエージェントを開発する。あわせて、文書に残らない現場の技を扱うフィジカルAIの研究開発（PoC）に取り組む。",
  foundingDate: "2026-08-08",
  foundingLocation: {
    "@type": "Place",
    address: { "@type": "PostalAddress", addressCountry: "JP",
               addressRegion: "群馬県", addressLocality: "高崎市" }
  },
  founder: { "@id": SITE_URL + "/about.html#founder" },
  employee: { "@id": SITE_URL + "/about.html#founder" },
  address: {
    "@type": "PostalAddress",
    addressCountry: "JP",
    addressRegion: "群馬県",
    addressLocality: "高崎市",
    streetAddress: "井野町360-7 オークスアベニューD201"
  },
  /* 会社概要とトップのCTAに既に出ている事実を、機械可読な形でも示す。
     電話は公開していないため申告しない。受付時間だけは公開済みで、
     地域事業者としての実在性を裏づける数少ない具体値になる。 */
  openingHoursSpecification: [{
    "@type": "OpeningHoursSpecification",
    dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    opens: "09:00",
    closes: "18:00"
  }],
  /* 事業を提供する地理範囲の宣言。本店は群馬県高崎市だが、対応は全国。
     AI検索が「群馬 AI導入支援」等へ分解して探索する際、住所だけでなく
     「その地域を対象に事業を行う主体」であることを機械可読な事実として示す。
     コピーは一切変えずに地域シグナルを補う手段。 */
  areaServed: [
    { "@type": "City", name: "高崎市" },
    { "@type": "AdministrativeArea", name: "群馬県" },
    { "@type": "AdministrativeArea", name: "北関東" },
    { "@type": "Country", name: "日本" }
  ],
  knowsAbout: [
    "暗黙知のAI化",
    "企業専用AIエージェント開発",
    "生成AI導入支援",
    "RAG構築",
    "大規模言語モデル(LLM)の最適化",
    "オンプレミスAI",
    "製造業のAI活用",
    "技術継承",
    "フィジカルAI"
  ]
};

/* 代表個人を独立したエンティティとして宣言する。
   「シンアイ 柴田昌国」「ShinAI 柴田」等の指名検索に対し、
   名前の文字列一致ではなく「シンアイ株式会社の代表である柴田昌国」という
   関係(worksFor/founder の相互参照)を機械可読な事実として示す。
   about.html に実体を置き、他ページからは @id で参照する。 */
const personLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": SITE_URL + "/about.html#founder",
  name: "柴田昌国",
  /* 姓名の分割表記と、検索で使われる表記ゆれを併記する。 */
  givenName: "昌国",
  familyName: "柴田",
  alternateName: ["柴田 昌国", "しばた まさくに", "Masakuni Shibata"],
  /* 経営者であると同時に自ら手を動かすAIエンジニアであることが差別化の核。
     検索・AI検索の双方が「肩書きだけの代表」と誤認しないよう両方を宣言する。 */
  jobTitle: ["代表取締役", "AIエンジニア"],
  hasOccupation: {
    "@type": "Occupation",
    name: "AIエンジニア",
    occupationalCategory: "AIエンジニア",
    description: "上場企業から中小企業まで、AIシステムの企画設計、開発、運用に従事。生成AIサービスの企画設計、RAG構築、AI活用戦略の立案を自ら手がける。"
  },
  description: "シンアイ株式会社 代表取締役／AIエンジニア。元消防士として約7年従事したのち、2023年2月から生成AIの可能性を確信しプログラミングを独学で習得。東京のAIシステム開発企業での実務を経て、2025年1月にShinAIを創業し、2026年8月に法人化。上場企業から中小企業まで、生成AIサービスの企画設計、RAG構築、AI活用戦略の立案を自ら手がけ、企業の暗黙知をAI資産へ変える支援に取り組む。",
  worksFor: { "@id": SITE_URL + "/#organization" },
  url: SITE_URL + "/about.html",
  image: SITE_URL + "/assets/images/ceo-masakuni-shibata.png",
  knowsAbout: [
    "生成AIサービスの企画設計",
    "RAG構築",
    "AI活用戦略の立案",
    "ビジネスプロセス最適化",
    "暗黙知のAI化",
    "企業専用AIエージェント開発",
    "AIシステムの受託開発",
    "AI導入支援"
  ],
  nationality: { "@type": "Country", name: "日本" },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressCountry: "JP",
      addressRegion: "群馬県",
      addressLocality: "高崎市"
    }
  }
};

const personLdEn = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": SITE_URL + "/about.html#founder",
  name: "Masakuni Shibata",
  givenName: "Masakuni",
  familyName: "Shibata",
  alternateName: ["柴田昌国", "柴田 昌国"],
  jobTitle: ["Founder and CEO", "AI Engineer"],
  hasOccupation: {
    "@type": "Occupation",
    name: "AI Engineer",
    occupationalCategory: "AI Engineer",
    description: "Designs, builds, and runs AI systems for clients ranging from listed companies to small and mid-sized firms. Hands-on across generative AI service design, RAG development, and AI strategy."
  },
  description: "Founder, CEO, and AI engineer at ShinAI Inc. A former firefighter of some seven years, he became convinced of what generative AI could do in February 2023 and taught himself to program. After working at an AI systems development company in Tokyo, he founded ShinAI in January 2025 and incorporated it in August 2026. He works hands-on across generative AI service design, RAG development, and AI strategy, turning the tacit knowledge inside companies into working AI assets.",
  worksFor: { "@id": SITE_URL + "/#organization" },
  url: SITE_URL + "/en/about.html",
  image: SITE_URL + "/assets/images/ceo-masakuni-shibata.png",
  knowsAbout: [
    "Generative AI service design",
    "Retrieval-augmented generation (RAG)",
    "AI strategy",
    "Business process optimisation",
    "Tacit knowledge structuring with AI",
    "Private enterprise AI agents",
    "Custom AI system development",
    "AI adoption support"
  ],
  nationality: { "@type": "Country", name: "Japan" },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressCountry: "JP",
      addressRegion: "Gunma",
      addressLocality: "Takasaki"
    }
  }
};

/* 英語版の Organization。海外の検索・AI検索が読む一次情報になるため、
   日本語版と同一の事実を英語で記述する(内容を盛らない)。 */
const ldJsonEn = {
  "@context": "https://schema.org",
  "@type": ["Organization", "ProfessionalService"],
  "@id": SITE_URL + "/#organization",
  name: "ShinAI Inc.",
  legalName: "ShinAI Inc.",
  alternateName: ["ShinAI", "シンアイ株式会社", "シンアイ"],
  identifier: {
    "@type": "PropertyValue",
    propertyID: "Japan Corporate Number (houjin bangou)",
    value: CORPORATE_NUMBER
  },
  sameAs: OFFICIAL_REFERENCES,
  url: SITE_URL + "/en/",
  email: CONTACT_EMAIL,
  logo: LOGO_IMAGE,
  image: LOGO_IMAGE,
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: CONTACT_EMAIL,
    availableLanguage: ["ja", "en"],
    areaServed: "JP"
  },
  slogan: "Turn your company's tacit knowledge into working AI assets.",
  description: "ShinAI is a Japan-based engineering team specialising in enterprise AI. We connect human intent with AI, honouring what a company has built while guiding what it becomes next. Through reinforcement learning, custom LLM optimisation, RAG, and on-premise deployment, we turn tacit knowledge into AI and build private enterprise AI agents. We also carry out physical AI research and development (PoC) for the skill that documents never captured.",
  foundingDate: "2026-08-08",
  foundingLocation: {
    "@type": "Place",
    address: { "@type": "PostalAddress", addressCountry: "JP",
               addressRegion: "Gunma", addressLocality: "Takasaki" }
  },
  founder: { "@id": SITE_URL + "/about.html#founder" },
  employee: { "@id": SITE_URL + "/about.html#founder" },
  address: {
    "@type": "PostalAddress",
    addressCountry: "JP",
    addressRegion: "Gunma",
    addressLocality: "Takasaki",
    streetAddress: "360-7 Ino-machi, Oaks Avenue D201"
  },
  openingHoursSpecification: [{
    "@type": "OpeningHoursSpecification",
    dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    opens: "09:00",
    closes: "18:00"
  }],
  areaServed: [
    { "@type": "City", name: "Takasaki" },
    { "@type": "AdministrativeArea", name: "Gunma" },
    { "@type": "AdministrativeArea", name: "Kita-Kanto" },
    { "@type": "Country", name: "Japan" }
  ],
  knowsAbout: [
    "Tacit knowledge structuring with AI",
    "Private enterprise AI agents",
    "Generative AI adoption",
    "Retrieval-augmented generation (RAG)",
    "Large language model optimisation",
    "On-premise AI",
    "AI for manufacturing",
    "Skill transfer and succession",
    "Physical AI"
  ]
};

/* 検索結果でのサイト名表示のため、トップページに WebSite を出す。 */
const websiteLd = (loc) => ({
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": SITE_URL + "/" + loc.dir + "#website",
  name: "ShinAI",
  alternateName: loc.code === "ja" ? "シンアイ" : "ShinAI Inc.",
  inLanguage: loc.htmlLang,
  url: SITE_URL + "/" + loc.dir,
  /* サイトを組織へ結ぶ。断片のままだと「このサイトは誰のものか」が
     機械には決まらず、指名検索でサイト名として扱われにくくなる。 */
  publisher: { "@id": SITE_URL + "/#organization" }
});

/* 書体の読み込み。ここは描画を止める位置にあるため、要らないものを置かない。

   日本語の書体は unicode-range で約120に分割して配信される。ウェイトを一つ増やすと
   @font-face が約120件・CSSが約111KB増え、それを描画前に解析することになる。
   実測(2026-08-25)で @font-face 877件・777KB。自社CSS(140KB)の5.5倍だった。

   Zen Old Mincho 700: 落とす。CSS全体で font-weight が 700・bold になる宣言は
     一つも無く(全42宣言を確認)、600 が読み込まれている以上そこから繰り上がることもない。
     到達不能な120件だった。
   Noto Sans JP 700: 残す。.legal__dt が 600 を要求するが 600 は読み込まれておらず、
     フォント照合規則により 700 へ繰り上がって実際に描画されている。落とすと
     規約ページの見た目が変わる。 */
const FONTS_CSS_URL = "https://fonts.googleapis.com/css2" +
  "?family=Zen+Old+Mincho:wght@500;600" +
  "&family=Noto+Sans+JP:wght@300;400;500;700" +
  "&family=Fraunces:opsz,wght@9..144,400;9..144,500" +
  "&family=Space+Grotesk:wght@400;500;600" +
  "&display=swap";

const escapeAttr = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");

/* ---- FAQPage 構造化データ ----
   外部AI・検索エンジンはFAQを信頼性評価と回答引用に使うため、schema.org/FAQPage を出力する。
   partial の Q&A を唯一の真実源として自動抽出し、本文との不一致を構造的に防ぐ。 */
const stripTags = (s) => s.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
const faqLdFor = (loc, part) => {
  const raw = read(loc.src + "/" + part);
  const re = /<span class="faq-item__q-text">([\s\S]*?)<\/span>[\s\S]*?<div class="faq-item__a">([\s\S]*?)<\/div>/g;
  const mainEntity = [];
  let m;
  while ((m = re.exec(raw)) !== null) {
    mainEntity.push({
      "@type": "Question",
      name: stripTags(m[1]),
      acceptedAnswer: { "@type": "Answer", text: stripTags(m[2]) }
    });
  }
  if (!mainEntity.length) return null;
  return { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: loc.htmlLang, mainEntity };
};

/* サブページのパンくず構造化データ(検索結果の階層表示用)。
   crumbParent を持つページ(お知らせの個別記事等)は 3階層で申告する。 */
const breadcrumbLd = (loc, page) => {
  const meta = loc.code === "ja" ? page : page.en;
  /* パンくずを持つかどうかは crumb の有無で決まる(トップだけが持たない)。
     以前はファイル名を名指しで例外扱いしていたため、ページを足すたびに漏れた。 */
  if (!meta || !meta.crumb) return null;
  const home = SITE_URL + "/" + loc.dir;
  const items = [
    { "@type": "ListItem", position: 1, name: loc.code === "ja" ? "ホーム" : "Home", item: home }
  ];
  if (meta.crumbParent) {
    items.push({ "@type": "ListItem", position: 2, name: meta.crumbParent.name,
                 item: SITE_URL + "/" + loc.dir + meta.crumbParent.file });
  }
  items.push({ "@type": "ListItem", position: items.length + 1, name: meta.crumb,
               item: SITE_URL + "/" + loc.dir + page.file });
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items
  };
};

/* お知らせ記事の NewsArticle。登壇・発表という一次情報を、AI検索が
   「いつ・誰が・どこで」を伴った事実として引用できる形で申告する。 */
const articleLd = (loc, page, canonical) => {
  const meta = loc.code === "ja" ? page : page.en;
  return {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    headline: meta.crumb,
    description: meta.desc,
    inLanguage: loc.htmlLang,
    datePublished: page.article.date,
    dateModified: page.article.date,
    image: SITE_URL + "/" + page.article.image,
    /* 著者は個人、発行者は組織。両者は別物であり、誰が書いたか分からない記事は
       AI検索にとって引用の重みが落ちる。専門性の裏付けは個人に宿る。 */
    author: { "@id": SITE_URL + "/about.html#founder" },
    publisher: { "@id": SITE_URL + "/#organization" },
    about: { "@id": SITE_URL + "/about.html#founder" },
    mainEntityOfPage: { "@type": "WebPage", "@id": canonical }
  };
};

/* お知らせ一覧の各項目を NewsArticle として申告する。
   詳細ページを持たない項目は、一覧内のアンカーを引用先URLにする。
   URLと日付が無い記述は、AI検索にとって引用できない情報と同じであり、
   「いつ・どこに書いてあるか」を伴わせて初めて、事実として扱われる。
   一覧の本文を唯一の出所として抽出するので、書き換えれば申告も追随する。 */
const newsListLd = (loc) => {
  const raw = read(loc.src + "/news.html");
  const base = SITE_URL + "/" + loc.dir + "news.html";
  /* 項目ごとに切ってから中身を拾う。一つの正規表現で通しに読むと、
     省略可能な <a href> が直前の貪欲でない一致に飛ばされ、
     詳細ページを持つ項目のURLが黙って落ちる(実際に落ちた)。 */
  const blocks = raw.split(/<li class="news__item/).slice(1);
  const field = (s, re) => { const m = s.match(re); return m ? m[1] : null; };
  const items = [];
  for (const block of blocks) {
    const date = field(block, /<time class="news__date" datetime="([^"]+)"/);
    const title = field(block, /<h3 class="news__title">([\s\S]*?)<\/h3>/);
    const text = field(block, /<p class="news__text">([\s\S]*?)<\/p>/);
    const img = field(block, /<img src="([^"]+)"/);
    if (!date || !title || !text || !img) continue;
    const anchor = field(block, /^[^>]*\sid="([^"]+)"/);
    const href = field(block, /<a class="news__link" href="([^"]+)"/);
    const url = href ? SITE_URL + "/" + loc.dir + href : base + (anchor ? "#" + anchor : "");
    items.push({
      "@type": "ListItem",
      position: items.length + 1,
      item: {
        "@type": "NewsArticle",
        headline: stripTags(title),
        description: stripTags(text),
        inLanguage: loc.htmlLang,
        datePublished: date,
        dateModified: date,
        image: SITE_URL + "/" + img.replace(/^\.\.\//, ""),
        url,
        author: { "@id": SITE_URL + "/about.html#founder" },
        publisher: { "@id": SITE_URL + "/#organization" },
        mainEntityOfPage: { "@type": "WebPage", "@id": url }
      }
    });
  }
  if (!items.length) return null;
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: loc.code === "ja" ? "ShinAIのお知らせ" : "News from ShinAI",
    inLanguage: loc.htmlLang,
    itemListElement: items
  };
};

/* ページそのものの申告。AI検索は引用の可否を「いつの情報か」で判断するため、
   本文と同じ出所(lastModOf)から dateModified を出す。
   組織・サイトへの所属を @id で結び、断片ではなく一つの実体として読ませる。 */
const webPageLd = (loc, page, canonical, lastMod) => {
  const meta = loc.code === "ja" ? page : page.en;
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": canonical,
    url: canonical,
    name: meta.title,
    description: meta.desc,
    inLanguage: loc.htmlLang,
    dateModified: lastMod,
    isPartOf: { "@type": "WebSite", "@id": SITE_URL + "/" + loc.dir + "#website" },
    publisher: { "@id": SITE_URL + "/#organization" }
  };
};

/* 提供サービスの申告。partial の見出しと導入文を唯一の真実源として抽出し、
   本文と構造化データが食い違う状態を作らない(FAQPage と同じ方針)。
   料金は公開していないため offers は置かない。無い値を型のために埋めない。 */
const serviceLdFor = (loc) => {
  const raw = read(loc.src + "/services.html");
  const re = /<h3 id="sol-[a-z]+-title" class="solution-card__title">([\s\S]*?)<\/h3>[\s\S]*?<p class="solution-card__lead">([\s\S]*?)<\/p>/g;
  const items = [];
  let m;
  while ((m = re.exec(raw)) !== null) {
    items.push({
      "@type": "Service",
      name: stripTags(m[1]),
      description: stripTags(m[2]),
      serviceType: stripTags(m[1]),
      provider: { "@id": SITE_URL + "/#organization" },
      /* 本店のある県と、実際に対応する全国の二つの粒度で示す。会社概要の
         「群馬県を中心に全国」と同じ事実を、役務ごとに機械可読へ落とす。 */
      areaServed: [
        { "@type": "AdministrativeArea", name: loc.code === "ja" ? "群馬県" : "Gunma" },
        { "@type": "Country", name: loc.code === "ja" ? "日本" : "Japan" }
      ]
    });
  }
  if (!items.length) return null;
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: loc.code === "ja" ? "ShinAIの提供サービス" : "Services offered by ShinAI",
    inLanguage: loc.htmlLang,
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem", position: i + 1, item
    }))
  };
};

/* 公開HTMLから HTMLコメントを除去(開発メモを出さない。doctypeは非対象)。 */
const stripComments = (html) => html.replace(/<!--[\s\S]*?-->/g, "").replace(/\n{3,}/g, "\n\n");

/* index.html は "/" と "/index.html" の両方で200を返すため、正規URLを
   ディレクトリ形式("/", "/en/")に統一する。両方を実体として残したまま
   canonical/hreflang/sitemap を一方へ集約し、重複コンテンツ評価を防ぐ。 */
const urlFor = (file, dir) =>
  SITE_URL + "/" + dir + (file === "index.html" ? "" : file);

const shell = (page, loc) => {
  const meta = loc.code === "ja" ? page : page.en;
  const canonical = urlFor(page.file, loc.dir);
  const main = normalizeMain(read(loc.src + "/" + page.part));
  /* replaceAll: partial 冒頭の解説コメント内にもトークン名が現れるため、先頭一致では取り違える。 */
  const header = markCurrent(shared[loc.code].header, page.nav)
    .replaceAll("{{LANG_SWITCH}}", langSwitch(loc, page));
  const v = "?v=" + BUILD_HASH;
  /* 英語版は /en/ 配下にあるため、共有アセットへは一段上がる。 */
  const p = loc.prefix;
  const scripts = [
    `<script src="${p}scripts/config.js${v}" defer></script>`,
    `<script src="${p}scripts/nav.js${v}" defer></script>`,
    `<script src="${p}scripts/main.js${v}" defer></script>`,
    `<script src="${p}scripts/chatbot.js${v}" defer></script>`
  ];
  if (page.hero) {
    /* 施主が愛する流動パーティクル。Three.js は自己ホスト(CDNではない)で script-src 'self' を維持。 */
    scripts.splice(3, 0,
      `<script src="${p}scripts/vendor/three.min.js${v}" defer></script>`,
      `<script src="${p}scripts/particles.js${v}" defer></script>`
    );
  }
  if (page.extraScripts) {
    for (const s of page.extraScripts) { scripts.push(s.replace('src="', 'src="' + p)); }
  }

  /* hreflang: 同一内容の言語別URLを相互申告する。x-default は日本語(本社所在地の言語)。
     これがないと、英語ページが日本語ページの重複と見なされ英語圏で埋もれる。
     一言語しか持たないページでは何も申告しない。相互申告の相手がいない状態で
     自分だけを alternate に挙げても情報はゼロで、実体のないURLを指せば害になる。 */
  const pageLocales = localesFor(page);
  const alternates = pageLocales.length < 2 ? "" :
    pageLocales.map((l) =>
      `  <link rel="alternate" hreflang="${l.htmlLang}" href="${urlFor(page.file, l.dir)}">`
    ).join("\n") + `\n  <link rel="alternate" hreflang="x-default" href="${urlFor(page.file, "")}">`;

  const crumbLd = breadcrumbLd(loc, page);
  const structured = [
    loc.code === "ja" ? ldJson : ldJsonEn,
    page.file === "index.html" ? websiteLd(loc) : null,
    webPageLd(loc, page, canonical, lastModOf(loc.src + "/" + page.part)),
    page.part === "services.html" ? serviceLdFor(loc) : null,
    page.part === "news.html" ? newsListLd(loc) : null,
    /* 代表individualの実体は about.html にのみ置く(重複申告を避ける)。
       他ページの founder/employee は @id 参照でここへ解決される。 */
    page.file === "about.html" ? (loc.code === "ja" ? personLd : personLdEn) : null,
    /* Q&Aを持つページはすべて FAQPage を出す(faq.html 専用ではない)。
       本文に faq-item が無いページでは faqLdFor が null を返す。 */
    faqLdFor(loc, page.part),
    page.article ? articleLd(loc, page, canonical) : null,
    crumbLd
  ].filter(Boolean)
   .map((o) => `  <script type="application/ld+json">${JSON.stringify(o)}</script>`)
   .join("\n");

  return `<!doctype html>
<html lang="${loc.htmlLang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, interactive-widget=resizes-content">
  <title>${meta.title}</title>
  <meta name="description" content="${escapeAttr(meta.desc)}">
  <link rel="canonical" href="${canonical}">
${alternates}
  <meta name="robots" content="index, follow">
  <meta name="theme-color" content="#3A5FEB">
  <meta name="format-detection" content="telephone=no">

  <meta http-equiv="Content-Security-Policy" content="${CSP_META}">
  <meta name="referrer" content="strict-origin-when-cross-origin">

  <meta property="og:type" content="website">
  <meta property="og:site_name" content="ShinAI">
  <meta property="og:locale" content="${loc.ogLocale}">
${pageLocales.filter((l) => l.code !== loc.code)
  .map((l) => `  <meta property="og:locale:alternate" content="${l.ogLocale}">`).join("\n")}
  <meta property="og:title" content="${escapeAttr(meta.title)}">
  <meta property="og:description" content="${escapeAttr(meta.ogDesc || meta.desc)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${OG_IMAGE}">
  <meta property="og:image:secure_url" content="${OG_IMAGE}">
  <meta property="og:image:type" content="image/png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="ShinAI">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escapeAttr(meta.title)}">
  <meta name="twitter:description" content="${escapeAttr(meta.ogDesc || meta.desc)}">
  <meta name="twitter:image" content="${OG_IMAGE}">
  <meta name="twitter:image:alt" content="ShinAI">

  <link rel="icon" href="${p}favicon.ico" sizes="any">
  <link rel="icon" href="${p}assets/icons/favicon.png?v=${BUILD_HASH}" type="image/png" sizes="256x256">
  <link rel="apple-touch-icon" href="${p}assets/icons/apple-touch-icon.png?v=${BUILD_HASH}">
  <link rel="manifest" href="site.webmanifest">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="${FONTS_CSS_URL}">
  <link rel="stylesheet" href="${p}styles/app.css${v}">

${structured}
</head>
<body${page.file === "index.html" ? ' class="is-home"' : ""}>
  <a class="skip-link" href="#main">${loc.code === "ja" ? "メインコンテンツへ" : "Skip to main content"}</a>
${header}
  <main id="main">
${main}
  </main>
${shared[loc.code].footer}
${shared[loc.code].chatbot}
  ${scripts.join("\n  ")}${analyticsOn ? `
  <!-- Cloudflare Web Analytics: Cookieを置かず、個人を追跡しない。 -->
  <script defer src="${CF_BEACON_HOST}/beacon.min.js" data-cf-beacon='{"token": "${WEB_ANALYTICS_TOKEN}"}'></script>` : ""}
</body>
</html>
`;
};

let built = 0;
for (const loc of LOCALES) {
  if (loc.dir) mkdirSync(join(ROOT, loc.dir), { recursive: true });
  for (const page of pages) {
    if (!localesFor(page).includes(loc)) continue;
    write(loc.dir + page.file, stripComments(shell(page, loc)));
    built += 1;
  }
}

/* ---- 4. SEO・メタファイル生成(SITE_URL を単一の真実源とする) ---- */
/* AI検索の巡回者を名指しで許可する。
   `User-agent: *` で足りるように見えるが、この種の巡回者は既定で拒否されている前提で
   運用される場面が増えており(CDNの一括遮断・雛形の robots)、明示は「読んでよい」の
   意思表示になる。学習用の収集(GPTBot・CCBot 等)と、回答時の参照(OAI-SearchBot・
   ChatGPT-User 等)は別物であり、当社は本文を読ませて引用されることが利益なので双方を許可する。 */
const AI_AGENTS = [
  "GPTBot", "OAI-SearchBot", "ChatGPT-User",
  "ClaudeBot", "Claude-User", "Claude-SearchBot",
  "PerplexityBot", "Perplexity-User",
  "Google-Extended", "Applebot-Extended", "Bingbot", "CCBot"
];
write("robots.txt",
  "User-agent: *\nAllow: /\n\n" +
  AI_AGENTS.map((a) => `User-agent: ${a}\nAllow: /\n`).join("\n") +
  `\nSitemap: ${SITE_URL}/sitemap.xml\n`);

/* llms.txt — 大規模言語モデル向けの案内。HTMLを解析させずに、
   何の会社で、どのURLに何が書いてあるかを平文で渡す。
   ページ定義(pages)を唯一の出所とするので、ページを足せばここも自動で増える。 */
/* 会社概要を本文の定義リストから抜き出す。最も問われ、最も短い事実であり、
   HTMLを解析させずに平文で渡せると引用の確度が上がる。
   本文を唯一の出所とするので、会社概要を直せばここも追随する。
   番地だけは公開方針に従って落とし、構造化データ側の県・市へ差し替える。 */
const companyFacts = () => {
  const raw = read("partials/about.html");
  const re = /<dt class="company__fact-term">([\s\S]*?)<\/dt>\s*<dd class="company__fact-desc">([\s\S]*?)<\/dd>/g;
  const rows = [];
  let m;
  while ((m = re.exec(raw)) !== null) {
    const term = stripTags(m[1]);
    const value = term === "所在地"
      ? ldJson.address.addressRegion + ldJson.address.addressLocality
      /* 本文では区切りの直後で改行しているため、タグを剥がすと空白が残る。 */
      : stripTags(m[2]).replace(/\s*／\s*/g, "／");
    if (term && value) rows.push(`- ${term}: ${value}`);
  }
  if (!rows.length) throw new Error("会社概要を抽出できない。company__fact の構造を確認する。");
  /* 同名の別法人が実在する(神奈川県のシンアイ株式会社)。商号と地名だけでは
     取り違えが起こるため、公的登記に対応する識別子を平文でも渡す。 */
  rows.push(`- 法人番号: ${CORPORATE_NUMBER}（国税庁法人番号公表サイトで確認可能）`);
  return rows;
};

const llmsTxt = [
  "# ShinAI（シンアイ株式会社）",
  "",
  "> 群馬県高崎市のAI開発会社。企業の暗黙知（属人化した判断・技能）を、"
  + "現場で使える専用AIへ変える。RAG構築、企業専用AIエージェント開発、"
  + "大規模言語モデルの最適化、オンプレミス／自社GPUでの学習に対応する。",
  "",
  "問い合わせ: " + CONTACT_EMAIL,
  "",
  "## 会社概要",
  ""
].concat(companyFacts()).concat([
  "",
  "## ページ",
  ""
]).concat(
  pages
    .filter((p) => p.file !== "privacy.html" && p.file !== "terms.html")
    .map((p) => `- [${p.title}](${urlFor(p.file, "")}): ${p.desc}`)
).concat([
  "",
  "## English",
  ""
]).concat(
  pages
    .filter((p) => p.file !== "privacy.html" && p.file !== "terms.html")
    .filter((p) => localesFor(p).some((l) => l.code === "en"))
    .map((p) => `- [${p.en.title}](${urlFor(p.file, "en/")}): ${p.en.desc}`)
).join("\n") + "\n";
write("llms.txt", llmsTxt);

/* 各URLに全言語版を xhtml:link で併記する(Google が推奨する言語版の申告方法)。
   HTMLの hreflang と二重に申告することで、英語圏の検索結果に英語版が出る確度を上げる。 */
write("sitemap.xml",
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' +
  LOCALES.flatMap((loc) => pages.filter((p) => localesFor(p).includes(loc)).map((p) => {
    /* 言語版を持たないページには xhtml:link を出さない。
       HTMLの hreflang と食い違うと、どちらが正しいか判定できなくなる。 */
    const langs = localesFor(p);
    const alts = langs.length < 2 ? "" : langs.map((l) =>
      `\n    <xhtml:link rel="alternate" hreflang="${l.htmlLang}" href="${urlFor(p.file, l.dir)}"/>`
    ).join("") +
    `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor(p.file, "")}"/>`;
    return `  <url>\n    <loc>${urlFor(p.file, loc.dir)}</loc>` + alts +
      `\n    <lastmod>${lastModOf(loc.src + "/" + p.part)}</lastmod>` +
      `\n    <changefreq>${p.changefreq}</changefreq>\n    <priority>${p.priority}</priority>\n  </url>`;
  })).join("\n") +
  "\n</urlset>\n");

write(".well-known/security.txt", [
  `Contact: mailto:${SECURITY_CONTACT_EMAIL}`,
  "Preferred-Languages: ja, en",
  `Canonical: ${SITE_URL}/.well-known/security.txt`,
  "Expires: 2027-06-30T00:00:00.000Z"
].join("\n") + "\n");

/* start_url はホスティングのサブパスに追従させる(GH Pages: /website-v2/、独自ドメイン: /)。
   ロケールごとに manifest を分けて生成する(icons/manifest はページと同階層に置き、
   href はプレフィックスなしの相対参照にする。英語版で日本語のPWA名/説明が出ないように)。 */
const BASE_PATH = new URL(SITE_URL).pathname.replace(/\/?$/, "/");
for (const loc of LOCALES) {
  write(loc.dir + "site.webmanifest", JSON.stringify({
    name: "ShinAI",
    short_name: "ShinAI",
    description: loc.manifestDesc,
    lang: loc.htmlLang,
    start_url: BASE_PATH + loc.dir,
    display: "standalone",
    background_color: "#060E1E",
    theme_color: "#3A5FEB",
    icons: [
      { src: loc.prefix + "assets/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: loc.prefix + "assets/icons/icon-512.png", sizes: "512x512", type: "image/png" }
    ]
  }, null, 2) + "\n");
}

/* ---- 5. 公開専用の dist/ を生成 ----
   公開対象のファイルのみを集めた清浄な出力ディレクトリを作る。 */
const DIST = join(ROOT, "dist");
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
const toDist = (rel) => {
  const dest = join(DIST, rel);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(join(ROOT, rel), dest);
};
for (const loc of LOCALES) {                           // 生成済みHTML(言語別)
  for (const page of pages) {
    if (!localesFor(page).includes(loc)) continue;
    toDist(loc.dir + page.file);
  }
}
toDist("styles/app.css");                              // 本番CSS(結合済み)
cpSync(join(ROOT, "scripts"), join(DIST, "scripts"), { recursive: true }); // 公開JS+vendor
cpSync(join(ROOT, "assets"), join(DIST, "assets"), { recursive: true });
/* favicon.ico はルート直下に置く。多くのブラウザ・検索エンジン・SNSは
   HTMLの<link rel="icon">を読まず /favicon.ico を直接取得しにいくため、
   ここが404だとタブや一覧にアイコンが出ない。 */
for (const f of ["robots.txt", "sitemap.xml", "llms.txt", "favicon.ico"]) toDist(f);
for (const loc of LOCALES) toDist(loc.dir + "site.webmanifest");
toDist(".well-known/security.txt");
/* 応答ヘッダ(Netlify/Cloudflare Pages形式)。CSPは上の単一定義から差し込み、
   deploy/_headers 側の {{CSP}} を置換する。二重管理をここで断つ。 */
writeFileSync(
  join(DIST, "_headers"),
  read("deploy/_headers").replace("{{CSP}}", CSP_HEADER),
  "utf8"
);

/* ---- 8. チャットボットの知識ベース ----
   公開ページの本文だけを抜き出し、AIが参照する唯一の事実源とする。
   ビルドで毎回作り直すため、サイトを直せば知識も自動で追従する
   (手書きのFAQを別に持つと必ず本体と乖離し、AIが古い事実を配る)。
   公開HTMLからの抽出なので、機密が混入する経路が構造的に存在しない。 */
/* 会社概要の定義リストだけは常時同梱にする。最も問われ、かつ最も短い。 */
const PIN_DL_PAGES = new Set(["about.html"]);

/* サービスの目次に添える前置きと結び。一覧そのものは見出しから自動生成する。
   フィジカルAIを落とさず、しかし三つの柱より先には出さない。
   訪問者が最初に受け取る順序が、そのまま会社の印象になる。 */
const CATALOG_TEXT = {
  ja: {
    title: "提供サービス一覧",
    lead: "ShinAIが法人向けに提供しているサービスは、次の三つです。",
    tail: "このほかに研究開発領域として、フィジカルAI（現場の動作や判断をAIが扱える形にする取り組み）のPoCを行っています。"
  },
  en: {
    title: "Services offered",
    lead: "ShinAI offers three services to companies.",
    tail: "Alongside these, we carry out physical AI research and development (PoC) on the skill that documents never captured."
  }
};

const knowledgeFor = (loc) => {
  const chunks = [];
  const catalog = CATALOG_TEXT[loc.code];
  for (const page of pages) {
    /* その言語で公開しないページは知識ベースにも入れない。
       生成していないHTMLを読もうとして落ちるだけでなく、
       チャットが存在しないURLを案内してしまう。 */
    if (!localesFor(page).includes(loc)) continue;
    const meta = loc.code === "ja" ? page : page.en;
    const html = read(loc.dir + page.file);
    const ctx = {
      title: meta.title,
      url: urlFor(page.file, loc.dir),
      slug: page.file.replace(/\.html$/, ""),
      pinDl: PIN_DL_PAGES.has(page.file)
    };
    /* 目次は本文チャンクより前に置く。渡した順序が、そのまま答えの順序になる。 */
    if (page.part === "services.html") {
      const c = catalogChunk(html, {
        ...ctx, catalogTitle: catalog.title,
        catalogLead: catalog.lead, catalogTail: catalog.tail
      });
      if (!c) throw new Error("サービス一覧を抽出できない。solution-card の構造を確認する。");
      chunks.push(c);
    }
    chunks.push(...chunkPage(html, ctx));
  }
  return { locale: loc.code, generatedAt: BUILD_HASH, chunks };
};

/* 埋め込みはビルド時に一度だけ確定させる。実行時に要るのは質問1件分の変換だけになり、
   Worker は外部の索引を持たずに済む(同期ずれも障害点も増えない)。
   鍵が無い環境ではベクトルを付けずに進める。検索は字面のみへ穏やかに縮退し、
   ビルドは止まらない(公開手順を鍵の有無に縛らない)。 */
const EMBED_MODEL = "text-embedding-3-small";
const EMBED_DIMS = 512;

/* 前回の生成物からベクトルを引き継ぐ。
   引き継ぎの鍵は題と本文そのもの(埋め込みの入力と同一)。文言が一字でも
   変われば鍵が変わり、古いベクトルが新しい文へ付くことはない。
   モデルか次元が変わっていれば全て捨てる。混在は静かな精度劣化になる。 */
const carryVectors = (locale, chunks) => {
  const path = join(ROOT, "api", `knowledge.${locale}.json`);
  if (!existsSync(path)) return 0;
  let prev;
  try {
    prev = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return 0;
  }
  if (prev.embedModel !== EMBED_MODEL || prev.embedDims !== EMBED_DIMS) return 0;
  const byText = new Map();
  for (const c of prev.chunks || []) {
    if (c.vec) byText.set(`${c.title}\n${c.text}`, c.vec);
  }
  let carried = 0;
  for (const c of chunks) {
    const vec = byText.get(`${c.title}\n${c.text}`);
    if (vec) {
      c.vec = vec;
      carried += 1;
    }
  }
  return carried;
};

const embedChunks = async (chunks) => {
  /* 鍵の有無に関わらず、まず引き継げるものを引き継ぐ。
     鍵なしのビルドが既存のベクトルを消していた。手順の誤り一つで
     検索が字面のみへ落ち、それが公開まで気づかれずに進む経路だった。 */
  const key = process.env.OPENAI_API_KEY;
  const pending = chunks.filter((c) => !c.vec);
  if (!pending.length) return true;
  if (!key) {
    /* 静かに縮退させない。鍵を渡したつもりで渡っていない取り違えが実際に起きた。
       縮退それ自体は正しい振る舞いだが、気づけないまま公開されると
       検索の精度だけが落ちた状態が続く。 */
    console.warn(
      `\n[注意] OPENAI_API_KEY が渡っていないため、${pending.length}件のベクトルを付けられません。` +
      "\n       文言を変えたチャンクだけが字面検索へ落ちます（言い換えは繋がりません）。" +
      "\n       このマシンに .env.local を置くと、以後は node _build/build.mjs だけで足ります:" +
      "\n         OPENAI_API_KEY=<鍵>   (リポジトリ直下・.gitignore 済み)" +
      "\n       一度きりなら、鍵の設定とビルドを同じコマンドで実行してください:" +
      "\n         $env:OPENAI_API_KEY = Read-Host \"OpenAI APIキー\"; node _build/build.mjs\n"
    );
    return false;
  }
  /* 題と本文を合わせて1件とする。題は検索の的として効きが強い。
     引き継げなかった分だけを送る。変えていない文へ費用を払わない。 */
  const res = await fetch("https://api.openai.com/v1/embeddings", {
    method: "POST",
    headers: { "Content-Type": "application/json", "Authorization": `Bearer ${key}` },
    body: JSON.stringify({
      model: EMBED_MODEL,
      input: pending.map((c) => `${c.title}\n${c.text}`),
      dimensions: EMBED_DIMS
    })
  });
  if (!res.ok) throw new Error(`embeddings failed: ${res.status} ${await res.text()}`);
  for (const item of (await res.json()).data) {
    pending[item.index].vec = encodeVector(normalizeVector(item.embedding));
  }
  return true;
};

/* Worker が import で同梱するため api/ 直下へ置く(こちらが実体)。
   dist/ 側にも出すのは、生成物をテストと目視で確認できるようにするため。 */
mkdirSync(join(DIST, "api"), { recursive: true });
for (const loc of LOCALES) {
  const kb = knowledgeFor(loc);
  carryVectors(loc.code, kb.chunks);
  await embedChunks(kb.chunks);
  /* 一件でもベクトルを持つなら索引としては有効。検索側はチャンク単位で
     ベクトルの有無を見るため、混在しても壊れない。 */
  const withVec = kb.chunks.filter((c) => c.vec).length;
  kb.embedModel = withVec ? EMBED_MODEL : null;
  kb.embedDims = withVec ? EMBED_DIMS : 0;
  const body = JSON.stringify(kb, null, 2);
  writeFileSync(join(ROOT, "api", `knowledge.${loc.code}.json`), body, "utf8");
  writeFileSync(join(DIST, "api", `knowledge.${loc.code}.json`), body, "utf8");
  const chars = kb.chunks.reduce((n, c) => n + c.text.length, 0);
  const state = withVec === kb.chunks.length
    ? `ベクトルあり(${EMBED_DIMS}次元)`
    : (withVec
      ? `ベクトル ${withVec}/${kb.chunks.length}件(未付与あり・公開前に鍵ありビルドが必要)`
      : "ベクトルなし(字面検索のみ)");
  console.log(
    `knowledge.${loc.code}.json: ${kb.chunks.length}チャンク / ${chars}字 / ${state}`
  );
}

console.log("built pages:", built);
console.log("app.css sections:", sectionFiles.length);
console.log("dist/ ready (publish this directory):", DIST);
