/*
  ShinAI Website v2 — build.mjs（開発ツール。公開ディレクトリには含めない）
  partials と styles を読み、共有シェルへ結合して各ページの最終HTMLを生成する。
  - CSS は tokens→base→sections の順で styles/app.css に結合(リクエスト削減)。
  - partials/<page>.html(=main の中身) を <main id="main"> で正規化して挿入。
  - 共有 head/header/footer/chatbot を全ページへ。現在地ナビに aria-current を付与。
  実行: node _build/build.mjs
*/
import { readFileSync, writeFileSync, readdirSync, cpSync, mkdirSync, rmSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/* ビルドごとにGitハッシュをURLクエリに付加してブラウザキャッシュを無効化する。 */
const BUILD_HASH = (() => {
  try { return execSync("git rev-parse --short HEAD", { cwd: ROOT }).toString().trim(); }
  catch { return Date.now().toString(36); }
})();

/* 実ドメインを置く唯一の場所。OGP/canonical の絶対URLに使う。 */
const SITE_URL = "https://shinai-inc.jp";
/* OGPクローラ(LINE等)はURL単位でキャッシュするため、画像を変えるときはファイル名も変える */
const OG_IMAGE = SITE_URL + "/assets/images/ogp-card-logo.png";
const CONTACT_EMAIL = "contact@shinai-inc.jp";
/* RFC 9116の脆弱性報告窓口。一般問い合わせ(CONTACT_EMAIL)とは意図的に分けている。 */
const SECURITY_CONTACT_EMAIL = "support@shinai-inc.jp";

const read = (p) => readFileSync(join(ROOT, p), "utf8");
const write = (p, c) => writeFileSync(join(ROOT, p), c, "utf8");

/* ---- 1. CSS 結合(tokens, base を先頭に) ---- */
const sectionsDir = join(ROOT, "styles", "sections");
const sectionFiles = readdirSync(sectionsDir).filter((f) => f.endsWith(".css")).sort();
let css = "/* Generated by _build/build.mjs — edit sources in styles/, not this file. */\n";
css += read("styles/tokens.css") + "\n";
css += read("styles/base.css") + "\n";
for (const f of sectionFiles) {
  css += "\n/* sections/" + f + " */\n" + read(join("styles", "sections", f)) + "\n";
}
write("styles/app.css", css);

/* ---- 2. ロケール定義 ----
   日本語はサイト直下、英語は /en/ 配下に出力する。既存の日本語URLを一切動かさずに
   英語版を増設でき、検索エンジンには言語ごとの独立URLとして正しくインデックスされる。
   dir     … SITE_URL からの出力先(末尾スラッシュ込み)
   prefix  … ページから見た共有アセット(styles/scripts/assets)への相対接頭辞
   src     … partial の読み込み元ディレクトリ */
const LOCALES = [
  { code: "ja", dir: "", prefix: "", src: "partials", htmlLang: "ja", ogLocale: "ja_JP",
    switchTo: "en", switchLabel: "English", switchAria: "Switch to English",
    manifestDesc: "企業の暗黙知を、使えるAI資産へ。" },
  { code: "en", dir: "en/", prefix: "../", src: "partials/en", htmlLang: "en", ogLocale: "en_US",
    switchTo: "ja", switchLabel: "日本語", switchAria: "日本語に切り替える",
    manifestDesc: "Turning your company's tacit knowledge into working AI assets." }
];

/* 言語切替UI。ヘッダーの {{LANG_SWITCH}} を置き換える。
   同一ページの他言語版へ1タップで移動する(トップへ飛ばさない)。 */
const langSwitch = (loc, file) => {
  const href = loc.code === "ja" ? "en/" + file : "../" + file;
  return `<a class="site-header__lang" href="${href}" hreflang="${loc.switchTo}" lang="${loc.switchTo}" aria-label="${loc.switchAria}">
        <svg class="site-header__lang-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.5"/>
          <path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18" stroke="currentColor" stroke-width="1.5"/>
        </svg>
        <span class="site-header__lang-label">${loc.switchLabel}</span>
      </a>`;
};

/* ロケールごとの共有 partial(ヘッダー/フッター/チャット)を読む。 */
const sharedFor = (loc) => ({
  header: read(loc.src + "/_header.html"),
  footer: read(loc.src + "/_footer.html").replace("{{YEAR}}", String(new Date().getFullYear())),
  chatbot: read(loc.src + "/_chatbot.html")
});
const shared = Object.fromEntries(LOCALES.map((l) => [l.code, sharedFor(l)]));

/* 現在地ナビに aria-current を付ける(最初の該当 href へ) */
const markCurrent = (html, nav) => {
  if (!nav) return html;
  const needle = `href="${nav}.html"`;
  const i = html.indexOf(needle);
  if (i === -1) return html;
  return html.slice(0, i + needle.length) + ' aria-current="page"' + html.slice(i + needle.length);
};

/* partials/<page> の <main> を正規化(既存の main タグを剥がして wrap し直す) */
const normalizeMain = (raw) =>
  raw.replace(/^\s*<main\b[^>]*>/i, "").replace(/<\/main>\s*$/i, "").trim();

/* ---- 3. ページ定義(sitemap の changefreq/priority もここで一元管理) ---- */
const pages = [
  { file: "index.html", part: "index.html", nav: null, hero: true,
    changefreq: "monthly", priority: "1.0",
    title: "ShinAI｜企業の暗黙知を、使えるAI資産へ",
    desc: "退職や属人化で失われる判断や知識を、現場で使える専用AIへ。文書に残らない現場の技を扱うフィジカルAIの研究開発（PoC）にも取り組んでいます。",
    /* SNS共有のプレビューは一瞬で読まれる。課題の描写から入らず
       「何をする会社か」を先頭で言い切る。検索結果用のdescとは役割が違う。 */
    ogDesc: "企業の構造変革を支援するAI企業｜シンアイ株式会社　企画設計・開発・運用まで一気通貫支援",
    en: { title: "ShinAI | Turn Your Company's Tacit Knowledge into Working AI",
          desc: "The judgment and know-how your company loses to retirement and key-person dependency, rebuilt as private AI that works on the floor. A Japan-based enterprise AI engineering partner, researching physical AI for the skill documents never captured.",
          ogDesc: "An AI company supporting structural change in business | ShinAI Inc. End-to-end support from service design through development to operations." } },
  { file: "services.html", part: "services.html", nav: "services", hero: false,
    crumb: "ソリューション",
    changefreq: "monthly", priority: "0.9",
    title: "ソリューション｜ShinAI",
    desc: "暗黙知のAI化、企業専用AIエージェント、AI化伴走支援、そしてフィジカルAIの研究開発（PoC）。集めて、つなぎ、現場で使えるところまで。ShinAIの提供領域と進め方。",
    en: {crumb: "Solutions",  title: "Solutions | ShinAI",
          desc: "Tacit knowledge structuring, private enterprise AI agents, hands-on support for AI-driven transformation, and physical AI research (PoC). Capture it, connect it, and make it usable where the work happens." } },
  { file: "industries.html", part: "industries.html", nav: "industries", hero: false,
    crumb: "業種別の活用",
    changefreq: "monthly", priority: "0.8",
    title: "業種別の活用｜ShinAI",
    desc: "製造、建設、介護や専門サービス、小売、医療福祉、教育、金融、不動産。業種ごとの困りごとと、暗黙知改善でどう変わるかの活用イメージ。",
    en: {crumb: "Industries",  title: "Industries | ShinAI",
          desc: "Manufacturing, construction, care and professional services, retail, healthcare, education, finance, and real estate. What breaks in each, and how tacit-knowledge AI changes it." } },
  { file: "about.html", part: "about.html", nav: "about", hero: false,
    crumb: "会社情報",
    changefreq: "monthly", priority: "0.7",
    title: "会社情報｜ShinAI",
    desc: "技術より先に、人を見る。ShinAIの目的、代表メッセージ、七つのShin、体制と会社概要。",
    en: {crumb: "About",  title: "About | ShinAI",
          desc: "People before technology. Our purpose, a message from the founder, the Seven Shin principles, our team, and company facts." } },
  { file: "faq.html", part: "faq.html", nav: "faq", hero: false,
    crumb: "よくあるご質問",
    changefreq: "monthly", priority: "0.6",
    extraScripts: ['<script src="scripts/faq.js" defer></script>'],
    title: "よくあるご質問｜ShinAI",
    desc: "はじめての方へ、費用と導入、開発の進め方、業種別の活用、サービス、そのほか。ShinAIへのよくある質問。",
    en: {crumb: "FAQ",  title: "FAQ | ShinAI",
          desc: "Getting started, cost and rollout, how we build, industry use, our services, and more. Common questions about working with ShinAI." } },
  { file: "contact.html", part: "contact.html", nav: "contact", hero: false,
    crumb: "お問い合わせ",
    changefreq: "monthly", priority: "0.8",
    extraScripts: ['<script src="scripts/contact-form.js" defer></script>'],
    title: "お問い合わせ・無料相談｜ShinAI",
    desc: "まだ要件が決まっていなくても構いません。現在の業務と知識資産から、AIの適用可能性を一緒に整理します。無料相談は30〜45分、事前準備は不要です。",
    en: {crumb: "Contact",  title: "Contact & Free Consultation | ShinAI",
          desc: "You do not need defined requirements to talk to us. We map where AI can apply from your current operations and knowledge assets. Free consultation, 30-45 minutes, no preparation needed." } },
  { file: "news.html", part: "news.html", nav: "news", hero: false,
    crumb: "お知らせ",
    changefreq: "monthly", priority: "0.6",
    title: "お知らせ｜ShinAI",
    desc: "シンアイ株式会社の登壇・発表・活動のお知らせ。群馬県高崎市を拠点に、暗黙知のAI化と企業専用AIエージェント開発に取り組んでいます。",
    en: {crumb: "News",  title: "News | ShinAI",
          desc: "Talks, announcements, and activities from ShinAI Inc. Based in Takasaki, Gunma, working on tacit-knowledge AI and private enterprise AI agents." } },
  { file: "news-20251205-takasaki-press.html", part: "news-20251205-takasaki-press.html",
    nav: "news", hero: false,
    crumb: "高崎商工会議所 第9回合同プレス発表会に登壇",
    crumbParent: { name: "お知らせ", file: "news.html" },
    article: { date: "2025-12-05", image: "assets/images/news-takasaki-press.jpg" },
    changefreq: "yearly", priority: "0.5",
    title: "高崎商工会議所 第9回合同プレス発表会に登壇しました｜ShinAI",
    desc: "2025年12月5日、高崎商工会議所の第9回合同プレス発表会にShinAI代表 柴田昌国が登壇し、「AIで人間らしい時間を取り戻す」という想いのもと、群馬県高崎市を拠点とする取り組みを発表しました。",
    en: {crumb: "Talk at the 9th Takasaki CCI joint press conference",
          crumbParent: { name: "News", file: "news.html" },
          title: "Talk at the 9th Takasaki CCI Joint Press Conference | ShinAI",
          desc: "On 5 December 2025, ShinAI founder Masakuni Shibata spoke at the 9th joint press conference of the Takasaki Chamber of Commerce and Industry, presenting the company's work under the idea of using AI to give people their human hours back." } },
  { file: "privacy.html", part: "privacy.html", nav: null, hero: false,
    crumb: "プライバシーポリシー",
    changefreq: "yearly", priority: "0.2",
    title: "プライバシーポリシー｜ShinAI",
    desc: "ShinAIの個人情報の取り扱いについて。",
    en: {crumb: "Privacy Policy",  title: "Privacy Policy | ShinAI",
          desc: "How ShinAI handles personal information." } },
  { file: "terms.html", part: "terms.html", nav: null, hero: false,
    crumb: "利用規約",
    changefreq: "yearly", priority: "0.2",
    title: "利用規約｜ShinAI",
    desc: "ShinAIウェブサイトの利用規約。",
    en: {crumb: "Terms of Use",  title: "Terms of Use | ShinAI",
          desc: "Terms of use for the ShinAI website." } }
];

const ldJson = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": SITE_URL + "/#organization",
  name: "シンアイ株式会社",
  legalName: "シンアイ株式会社",
  /* 指名検索の表記ゆれ(シンアイ/ShinAI/シンアイ株式会社)を同一主体として束ねる。 */
  alternateName: ["ShinAI", "シンアイ", "ShinAI Inc.", "シンアイ"],
  url: SITE_URL + "/",
  email: CONTACT_EMAIL,
  slogan: "企業の暗黙知を、使えるAI資産へ。",
  description: "真の価値を信じ、次世代のために新たな未来を創る。ShinAIは、人の想いとAIをつなぎ、企業の「これまで」を大切に「これから」の変革に伴走する、企業AI開発特化のエンジニアチーム。強化学習・カスタムLLM最適化・RAG・オンプレミス対応により、暗黙知のAI化と企業専用AIエージェントを開発する。あわせて、文書に残らない現場の技を扱うフィジカルAIの研究開発（PoC）に取り組む。",
  foundingDate: "2026-08-08",
  founder: { "@id": SITE_URL + "/about.html#founder" },
  employee: { "@id": SITE_URL + "/about.html#founder" },
  address: {
    "@type": "PostalAddress",
    addressCountry: "JP",
    addressRegion: "群馬県",
    addressLocality: "高崎市",
    streetAddress: "井野町360-7 オークスアベニューD201"
  },
  /* 事業を提供する地理範囲の宣言。本店は群馬県高崎市だが、対応は全国。
     AI検索が「群馬 AI導入支援」等へ分解して探索する際、住所だけでなく
     「その地域を対象に事業を行う主体」であることを機械可読な事実として示す。
     コピーは一切変えずに地域シグナルを補う手段。 */
  areaServed: [
    { "@type": "AdministrativeArea", name: "群馬県" },
    { "@type": "AdministrativeArea", name: "北関東" },
    { "@type": "Country", name: "日本" }
  ],
  knowsAbout: [
    "暗黙知のAI化",
    "企業専用AIエージェント開発",
    "生成AI導入支援",
    "RAG構築",
    "大規模言語モデル(LLM)の最適化",
    "オンプレミスAI",
    "製造業のAI活用",
    "技術継承",
    "フィジカルAI"
  ]
};

/* 代表個人を独立したエンティティとして宣言する。
   「シンアイ 柴田昌国」「ShinAI 柴田」等の指名検索に対し、
   名前の文字列一致ではなく「シンアイ株式会社の代表である柴田昌国」という
   関係(worksFor/founder の相互参照)を機械可読な事実として示す。
   about.html に実体を置き、他ページからは @id で参照する。 */
const personLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": SITE_URL + "/about.html#founder",
  name: "柴田昌国",
  /* 姓名の分割表記と、検索で使われる表記ゆれを併記する。 */
  givenName: "昌国",
  familyName: "柴田",
  alternateName: ["柴田 昌国", "しばた まさくに", "Masakuni Shibata"],
  /* 経営者であると同時に自ら手を動かすAIエンジニアであることが差別化の核。
     検索・AI検索の双方が「肩書きだけの代表」と誤認しないよう両方を宣言する。 */
  jobTitle: ["代表取締役", "AIエンジニア"],
  hasOccupation: {
    "@type": "Occupation",
    name: "AIエンジニア",
    occupationalCategory: "AIエンジニア",
    description: "上場企業から中小企業まで、AIシステムの企画設計、開発、運用に従事。生成AIサービスの企画設計、RAG構築、AI活用戦略の立案を自ら手がける。"
  },
  description: "シンアイ株式会社 代表取締役／AIエンジニア。元消防士として約7年従事したのち、2023年2月から生成AIの可能性を確信しプログラミングを独学で習得。東京のAIシステム開発企業での実務を経て、2025年1月にShinAIを創業し、2026年8月に法人化。上場企業から中小企業まで、生成AIサービスの企画設計、RAG構築、AI活用戦略の立案を自ら手がけ、企業の暗黙知をAI資産へ変える支援に取り組む。",
  worksFor: { "@id": SITE_URL + "/#organization" },
  url: SITE_URL + "/about.html",
  image: SITE_URL + "/assets/images/ceo-masakuni-shibata.png",
  knowsAbout: [
    "生成AIサービスの企画設計",
    "RAG構築",
    "AI活用戦略の立案",
    "ビジネスプロセス最適化",
    "暗黙知のAI化",
    "企業専用AIエージェント開発",
    "AIシステムの受託開発",
    "AI導入支援"
  ],
  nationality: { "@type": "Country", name: "日本" },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressCountry: "JP",
      addressRegion: "群馬県",
      addressLocality: "高崎市"
    }
  }
};

const personLdEn = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": SITE_URL + "/about.html#founder",
  name: "Masakuni Shibata",
  givenName: "Masakuni",
  familyName: "Shibata",
  alternateName: ["柴田昌国", "柴田 昌国"],
  jobTitle: ["Founder and CEO", "AI Engineer"],
  hasOccupation: {
    "@type": "Occupation",
    name: "AI Engineer",
    occupationalCategory: "AI Engineer",
    description: "Designs, builds, and runs AI systems for clients ranging from listed companies to small and mid-sized firms. Hands-on across generative AI service design, RAG development, and AI strategy."
  },
  description: "Founder, CEO, and AI engineer at ShinAI Inc. A former firefighter of some seven years, he became convinced of what generative AI could do in February 2023 and taught himself to program. After working at an AI systems development company in Tokyo, he founded ShinAI in January 2025 and incorporated it in August 2026. He works hands-on across generative AI service design, RAG development, and AI strategy, turning the tacit knowledge inside companies into working AI assets.",
  worksFor: { "@id": SITE_URL + "/#organization" },
  url: SITE_URL + "/en/about.html",
  image: SITE_URL + "/assets/images/ceo-masakuni-shibata.png",
  knowsAbout: [
    "Generative AI service design",
    "Retrieval-augmented generation (RAG)",
    "AI strategy",
    "Business process optimisation",
    "Tacit knowledge structuring with AI",
    "Private enterprise AI agents",
    "Custom AI system development",
    "AI adoption support"
  ],
  nationality: { "@type": "Country", name: "Japan" },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressCountry: "JP",
      addressRegion: "Gunma",
      addressLocality: "Takasaki"
    }
  }
};

/* 英語版の Organization。海外の検索・AI検索が読む一次情報になるため、
   日本語版と同一の事実を英語で記述する(内容を盛らない)。 */
const ldJsonEn = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": SITE_URL + "/#organization",
  name: "ShinAI Inc.",
  legalName: "ShinAI Inc.",
  alternateName: ["ShinAI", "シンアイ株式会社", "シンアイ"],
  url: SITE_URL + "/en/",
  email: CONTACT_EMAIL,
  slogan: "Turn your company's tacit knowledge into working AI assets.",
  description: "ShinAI is a Japan-based engineering team specialising in enterprise AI. We connect human intent with AI, honouring what a company has built while guiding what it becomes next. Through reinforcement learning, custom LLM optimisation, RAG, and on-premise deployment, we turn tacit knowledge into AI and build private enterprise AI agents. We also carry out physical AI research and development (PoC) for the skill that documents never captured.",
  foundingDate: "2026-08-08",
  founder: { "@id": SITE_URL + "/about.html#founder" },
  employee: { "@id": SITE_URL + "/about.html#founder" },
  address: {
    "@type": "PostalAddress",
    addressCountry: "JP",
    addressRegion: "Gunma",
    addressLocality: "Takasaki",
    streetAddress: "360-7 Ino-machi, Oaks Avenue D201"
  },
  areaServed: [
    { "@type": "AdministrativeArea", name: "Gunma" },
    { "@type": "AdministrativeArea", name: "Kita-Kanto" },
    { "@type": "Country", name: "Japan" }
  ],
  knowsAbout: [
    "Tacit knowledge structuring with AI",
    "Private enterprise AI agents",
    "Generative AI adoption",
    "Retrieval-augmented generation (RAG)",
    "Large language model optimisation",
    "On-premise AI",
    "AI for manufacturing",
    "Skill transfer and succession",
    "Physical AI"
  ]
};

/* 検索結果でのサイト名表示のため、トップページに WebSite を出す。 */
const websiteLd = (loc) => ({
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "ShinAI",
  alternateName: loc.code === "ja" ? "シンアイ" : "ShinAI Inc.",
  inLanguage: loc.htmlLang,
  url: SITE_URL + "/" + loc.dir
});

const escapeAttr = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");

/* ---- FAQPage 構造化データ ----
   外部AI・検索エンジンはFAQを信頼性評価と回答引用に使うため、schema.org/FAQPage を出力する。
   partial の Q&A を唯一の真実源として自動抽出し、本文との不一致を構造的に防ぐ。 */
const stripTags = (s) => s.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
const faqLdFor = (loc) => {
  const raw = read(loc.src + "/faq.html");
  const re = /<span class="faq-item__q-text">([\s\S]*?)<\/span>[\s\S]*?<div class="faq-item__a">([\s\S]*?)<\/div>/g;
  const mainEntity = [];
  let m;
  while ((m = re.exec(raw)) !== null) {
    mainEntity.push({
      "@type": "Question",
      name: stripTags(m[1]),
      acceptedAnswer: { "@type": "Answer", text: stripTags(m[2]) }
    });
  }
  return { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: loc.htmlLang, mainEntity };
};

/* サブページのパンくず構造化データ(検索結果の階層表示用)。
   crumbParent を持つページ(お知らせの個別記事等)は 3階層で申告する。 */
const breadcrumbLd = (loc, page) => {
  if (!page.nav && page.file !== "privacy.html" && page.file !== "terms.html") return null;
  const home = SITE_URL + "/" + loc.dir;
  const meta = loc.code === "ja" ? page : page.en;
  const items = [
    { "@type": "ListItem", position: 1, name: loc.code === "ja" ? "ホーム" : "Home", item: home }
  ];
  if (meta.crumbParent) {
    items.push({ "@type": "ListItem", position: 2, name: meta.crumbParent.name,
                 item: SITE_URL + "/" + loc.dir + meta.crumbParent.file });
  }
  items.push({ "@type": "ListItem", position: items.length + 1, name: meta.crumb,
               item: SITE_URL + "/" + loc.dir + page.file });
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items
  };
};

/* お知らせ記事の NewsArticle。登壇・発表という一次情報を、AI検索が
   「いつ・誰が・どこで」を伴った事実として引用できる形で申告する。 */
const articleLd = (loc, page, canonical) => {
  const meta = loc.code === "ja" ? page : page.en;
  return {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    headline: meta.crumb,
    description: meta.desc,
    inLanguage: loc.htmlLang,
    datePublished: page.article.date,
    dateModified: page.article.date,
    image: SITE_URL + "/" + page.article.image,
    author: { "@id": SITE_URL + "/#organization" },
    publisher: { "@id": SITE_URL + "/#organization" },
    /* 登壇者を代表個人へ紐付け、指名検索での実績の裏付けにする。 */
    about: { "@id": SITE_URL + "/about.html#founder" },
    mainEntityOfPage: { "@type": "WebPage", "@id": canonical }
  };
};

/* 公開HTMLから HTMLコメントを除去(開発メモを出さない。doctypeは非対象)。 */
const stripComments = (html) => html.replace(/<!--[\s\S]*?-->/g, "").replace(/\n{3,}/g, "\n\n");

/* index.html は "/" と "/index.html" の両方で200を返すため、正規URLを
   ディレクトリ形式("/", "/en/")に統一する。両方を実体として残したまま
   canonical/hreflang/sitemap を一方へ集約し、重複コンテンツ評価を防ぐ。 */
const urlFor = (file, dir) =>
  SITE_URL + "/" + dir + (file === "index.html" ? "" : file);

const shell = (page, loc) => {
  const meta = loc.code === "ja" ? page : page.en;
  const canonical = urlFor(page.file, loc.dir);
  const main = normalizeMain(read(loc.src + "/" + page.part));
  /* replaceAll: partial 冒頭の解説コメント内にもトークン名が現れるため、先頭一致では取り違える。 */
  const header = markCurrent(shared[loc.code].header, page.nav)
    .replaceAll("{{LANG_SWITCH}}", langSwitch(loc, page.file));
  const v = "?v=" + BUILD_HASH;
  /* 英語版は /en/ 配下にあるため、共有アセットへは一段上がる。 */
  const p = loc.prefix;
  const scripts = [
    `<script src="${p}scripts/config.js${v}" defer></script>`,
    `<script src="${p}scripts/nav.js${v}" defer></script>`,
    `<script src="${p}scripts/main.js${v}" defer></script>`,
    `<script src="${p}scripts/chatbot.js${v}" defer></script>`
  ];
  if (page.hero) {
    /* 施主が愛する流動パーティクル。Three.js は自己ホスト(CDNではない)で script-src 'self' を維持。 */
    scripts.splice(3, 0,
      `<script src="${p}scripts/vendor/three.min.js${v}" defer></script>`,
      `<script src="${p}scripts/particles.js${v}" defer></script>`
    );
  }
  if (page.extraScripts) {
    for (const s of page.extraScripts) { scripts.push(s.replace('src="', 'src="' + p)); }
  }

  /* hreflang: 同一内容の言語別URLを相互申告する。x-default は日本語(本社所在地の言語)。
     これがないと、英語ページが日本語ページの重複と見なされ英語圏で埋もれる。 */
  const alternates = LOCALES.map((l) =>
    `  <link rel="alternate" hreflang="${l.htmlLang}" href="${urlFor(page.file, l.dir)}">`
  ).join("\n") + `\n  <link rel="alternate" hreflang="x-default" href="${urlFor(page.file, "")}">`;

  const crumbLd = breadcrumbLd(loc, page);
  const structured = [
    loc.code === "ja" ? ldJson : ldJsonEn,
    page.file === "index.html" ? websiteLd(loc) : null,
    /* 代表individualの実体は about.html にのみ置く(重複申告を避ける)。
       他ページの founder/employee は @id 参照でここへ解決される。 */
    page.file === "about.html" ? (loc.code === "ja" ? personLd : personLdEn) : null,
    page.part === "faq.html" ? faqLdFor(loc) : null,
    page.article ? articleLd(loc, page, canonical) : null,
    crumbLd
  ].filter(Boolean)
   .map((o) => `  <script type="application/ld+json">${JSON.stringify(o)}</script>`)
   .join("\n");

  return `<!doctype html>
<html lang="${loc.htmlLang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, interactive-widget=resizes-content">
  <title>${meta.title}</title>
  <meta name="description" content="${escapeAttr(meta.desc)}">
  <link rel="canonical" href="${canonical}">
${alternates}
  <meta name="robots" content="index, follow">
  <meta name="theme-color" content="#3A5FEB">
  <meta name="format-detection" content="telephone=no">

  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://formspree.io; base-uri 'self'; form-action 'self' https://formspree.io; object-src 'none'">
  <meta name="referrer" content="strict-origin-when-cross-origin">

  <meta property="og:type" content="website">
  <meta property="og:site_name" content="ShinAI">
  <meta property="og:locale" content="${loc.ogLocale}">
  <meta property="og:locale:alternate" content="${LOCALES.find((l) => l.code !== loc.code).ogLocale}">
  <meta property="og:title" content="${escapeAttr(meta.title)}">
  <meta property="og:description" content="${escapeAttr(meta.ogDesc || meta.desc)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${OG_IMAGE}">
  <meta property="og:image:secure_url" content="${OG_IMAGE}">
  <meta property="og:image:type" content="image/png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="ShinAI">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escapeAttr(meta.title)}">
  <meta name="twitter:description" content="${escapeAttr(meta.ogDesc || meta.desc)}">
  <meta name="twitter:image" content="${OG_IMAGE}">
  <meta name="twitter:image:alt" content="ShinAI">

  <link rel="icon" href="${p}favicon.ico" sizes="any">
  <link rel="icon" href="${p}assets/icons/favicon.png?v=${BUILD_HASH}" type="image/png" sizes="256x256">
  <link rel="apple-touch-icon" href="${p}assets/icons/apple-touch-icon.png?v=${BUILD_HASH}">
  <link rel="manifest" href="site.webmanifest">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Zen+Old+Mincho:wght@500;600;700&family=Noto+Sans+JP:wght@300;400;500;700&family=Fraunces:opsz,wght@9..144,400;9..144,500&family=Space+Grotesk:wght@400;500;600&display=swap">
  <link rel="stylesheet" href="${p}styles/app.css${v}">

${structured}
</head>
<body${page.file === "index.html" ? ' class="is-home"' : ""}>
  <a class="skip-link" href="#main">${loc.code === "ja" ? "メインコンテンツへ" : "Skip to main content"}</a>
${header}
  <main id="main">
${main}
  </main>
${shared[loc.code].footer}
${shared[loc.code].chatbot}
  ${scripts.join("\n  ")}
</body>
</html>
`;
};

let built = 0;
for (const loc of LOCALES) {
  if (loc.dir) mkdirSync(join(ROOT, loc.dir), { recursive: true });
  for (const page of pages) {
    write(loc.dir + page.file, stripComments(shell(page, loc)));
    built += 1;
  }
}

/* ---- 4. SEO・メタファイル生成(SITE_URL を単一の真実源とする) ---- */
write("robots.txt", `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`);

/* 各URLに全言語版を xhtml:link で併記する(Google が推奨する言語版の申告方法)。
   HTMLの hreflang と二重に申告することで、英語圏の検索結果に英語版が出る確度を上げる。 */
write("sitemap.xml",
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' +
  LOCALES.flatMap((loc) => pages.map((p) => {
    const alts = LOCALES.map((l) =>
      `\n    <xhtml:link rel="alternate" hreflang="${l.htmlLang}" href="${urlFor(p.file, l.dir)}"/>`
    ).join("") +
    `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor(p.file, "")}"/>`;
    return `  <url>\n    <loc>${urlFor(p.file, loc.dir)}</loc>` + alts +
      `\n    <changefreq>${p.changefreq}</changefreq>\n    <priority>${p.priority}</priority>\n  </url>`;
  })).join("\n") +
  "\n</urlset>\n");

write(".well-known/security.txt", [
  `Contact: mailto:${SECURITY_CONTACT_EMAIL}`,
  "Preferred-Languages: ja, en",
  `Canonical: ${SITE_URL}/.well-known/security.txt`,
  "Expires: 2027-06-30T00:00:00.000Z"
].join("\n") + "\n");

/* start_url はホスティングのサブパスに追従させる(GH Pages: /website-v2/、独自ドメイン: /)。
   ロケールごとに manifest を分けて生成する(icons/manifest はページと同階層に置き、
   href はプレフィックスなしの相対参照にする。英語版で日本語のPWA名/説明が出ないように)。 */
const BASE_PATH = new URL(SITE_URL).pathname.replace(/\/?$/, "/");
for (const loc of LOCALES) {
  write(loc.dir + "site.webmanifest", JSON.stringify({
    name: "ShinAI",
    short_name: "ShinAI",
    description: loc.manifestDesc,
    lang: loc.htmlLang,
    start_url: BASE_PATH + loc.dir,
    display: "standalone",
    background_color: "#060E1E",
    theme_color: "#3A5FEB",
    icons: [
      { src: loc.prefix + "assets/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: loc.prefix + "assets/icons/icon-512.png", sizes: "512x512", type: "image/png" }
    ]
  }, null, 2) + "\n");
}

/* ---- 5. 公開専用の dist/ を生成 ----
   公開対象のファイルのみを集めた清浄な出力ディレクトリを作る。 */
const DIST = join(ROOT, "dist");
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
const toDist = (rel) => {
  const dest = join(DIST, rel);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(join(ROOT, rel), dest);
};
for (const loc of LOCALES) {                           // 生成済みHTML(日本語8 + 英語8)
  for (const page of pages) toDist(loc.dir + page.file);
}
toDist("styles/app.css");                              // 本番CSS(結合済み)
cpSync(join(ROOT, "scripts"), join(DIST, "scripts"), { recursive: true }); // 公開JS+vendor
cpSync(join(ROOT, "assets"), join(DIST, "assets"), { recursive: true });
/* favicon.ico はルート直下に置く。多くのブラウザ・検索エンジン・SNSは
   HTMLの<link rel="icon">を読まず /favicon.ico を直接取得しにいくため、
   ここが404だとタブや一覧にアイコンが出ない。 */
for (const f of ["robots.txt", "sitemap.xml", "favicon.ico"]) toDist(f);
for (const loc of LOCALES) toDist(loc.dir + "site.webmanifest");
toDist(".well-known/security.txt");
copyFileSync(join(ROOT, "deploy", "_headers"), join(DIST, "_headers")); // Netlify/CF用ヘッダ

console.log("built pages:", built);
console.log("app.css sections:", sectionFiles.length);
console.log("dist/ ready (publish this directory):", DIST);
